version: "3.5"
services:
  react-app:
    image: react-app
    ports:
      - 5000:5000
    depends_on:
      - backend
  backend:
    image: backend
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=user123
      - DB_PASSWORD=password123
      - DB_HOST=postgres
  redis:
    image: redis
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
