version: "3.5"
services:
  react-app:
    image: react-app
    ports:
      - 5000:5000
    depends_on:
      - backend
    environment:
      - API_URL=/api/
  backend:
    image: backend
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=user123
      - DB_PASSWORD=password123
      - DB_HOST=postgres
  redis:
    image: redis
    depends_on:
      - postgres
    volumes:
      - "./data/redis:/data"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    volumes:
      - ./data/postgres:/var/lib/posgresql/data
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - react-app
